function setup_paths()
    % SETUP_PATHS - Dodaje wszystkie niezbędne podfoldery do ścieżki MATLAB-a
    
    currentPath = fileparts(mfilename('fullpath'));
    
    % Lista folderów z algorytmami i metrykami
    folders = { ...
        'metrics', ...
        'AES', ...
        'DES', ...
        'blowfish', ...
        'chacha', ...
        'chaos_circular', ...
        'chaos_maps', ...
        'chaos_bit_shuffling', ...
        'chaos_2d', ...
        'chaos_logistic' ...
    };

    for i = 1:length(folders)
        folderPath = fullfile(currentPath, folders{i});
        if exist(folderPath, 'dir')
            addpath(folderPath);
        else
            warning('Folder nie istnieje: %s', folderPath);
        end
    end
    
    % Zapisz zmiany w ścieżce na czas sesji
    % savepath; % Opcjonalne, jeśli chcesz zapisać na stałe
end